USE DWBG
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE Colegio(
	IDColegio INT NOT NULL,
	Nombre VARCHAR(250) NOT NULL,
	IDCalendario  INT NOT NULL,
	Calendario VARCHAR(10) NOT NULL,
	Codigo	INT NOT NULL,
	Clave VARCHAR(250) NOT NULL,
	Dane VARCHAR(250) NOT NULL,
	IDNaturaleza INT NOT NULL,
	Naturaleza	VARCHAR(250) NOT NULL,
	IDRegional INT NOT NULL,
	Regional VARCHAR(250) NOT NULL,	
	IDDepartamento INT NOT NULL,
	Departamento VARCHAR(250) NOT NULL,	
	IDCiudad INT NOT NULL,
	Ciudad	VARCHAR(250) NOT NULL,
	IDLocalidad	INT NOT NULL,
	Localidad VARCHAR(250) NOT NULL,
	IDEstado INT NOT NULL,
	Estado VARCHAR(250) NOT NULL,
	Direccion VARCHAR(250) NOT NULL,
	Telefono VARCHAR(250) NOT NULL,
	Email VARCHAR(250) NOT NULL,
	NIT	VARCHAR(250) NOT NULL,
	IDGrupoEducativo  INT NOT NULL,
	GrupoEducativo  INT NOT NULL,
	IDJornada  INT NOT NULL,
	Jornada	VARCHAR(250) NOT NULL,
	IDTipoZona  INT NOT NULL, 
	TipoZona VARCHAR(250) NOT NULL,
	IDTipoEstablecimiento  INT NOT NULL,
	TipoEstablecimiento	VARCHAR(250) NOT NULL,
	IDGenero  INT NOT NULL,
	Genero	VARCHAR(250) NOT NULL,
	IDEstrato  INT NOT NULL,
	Estrato	VARCHAR(250) NOT NULL,
	IDNivelIcfes  INT NOT NULL,	
	NivelIcfes VARCHAR(250) NOT NULL,
	IDCaracter  INT NOT NULL,	
	Caracter	VARCHAR(250) NOT NULL,
	IDEspecialidad  INT NOT NULL,	
	Especialidad VARCHAR(250) NOT NULL,	
	IDGrupoAAMO	 INT NOT NULL,
	FechaActualizacion 	DATETIME NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	IDPais	 INT NOT NULL,
	Pais VARCHAR(250) NOT NULL,
	IDZonaDespacho  INT NOT NULL,	
	ZonaDespacho VARCHAR(250) NOT NULL,	
	AnioLectivo VARCHAR(250) NOT NULL,	
	EjecutivoComercial VARCHAR(250) NOT NULL,	
	Rector VARCHAR(250) NOT NULL,
	RectorEmail VARCHAR(250) NOT NULL,
	RectorTelefono VARCHAR(250) NOT NULL,
	Coordinador VARCHAR(250) NOT NULL,
	CoordinadorEmail VARCHAR(250) NOT NULL,	
	CoordinadorTelefono VARCHAR(250) NOT NULL,
	Encargado VARCHAR(250) NOT NULL,	
	EncargadoEmail VARCHAR(250) NOT NULL,
	EncargadoTelefono VARCHAR(250) NOT NULL,
 CONSTRAINT [PK_Colegio] PRIMARY KEY CLUSTERED 
(
	[IDColegio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
